### ISSUE TITLE
Failing to generate when weather fails

### ISSUE THREAD

**Issue by troykelly** [troykelly/live-news-break#74]
```text
ERROR:root:An error occurred during scheduled news generation: 'minutely'
ERROR:root:Traceback (most recent call last):
  File "/app/src/main.py", line 1851, in main
    generate_news_audio()
  File "/app/src/main.py", line 1459, in generate_news_audio
    weather_info = generate_openweather_weather_report(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/main.py", line 646, in generate_openweather_weather_report
    minutely_weather = data["minutely"]
                       ~~~~^^^^^^^^^^^^
KeyError: 'minutely'
```

**Comment by troykelly** [comment]
Error is back...

```text
ERROR:root:An error occurred during scheduled news generation: 'minutely'
ERROR:root:Traceback (most recent call last):
  File "/app/src/main.py", line 1851, in main
    generate_news_audio()
  File "/app/src/main.py", line 1459, in generate_news_audio
    weather_info = generate_openweather_weather_report(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/main.py", line 646, in generate_openweather_weather_report
    minutely_weather = data["minutely"]
                       ~~~~^^^^^^^^^^^^
KeyError: 'minutely'
```
